name: Fisherman's Blog
description: It's Never too late to learn
keywords: Python, Bash
baseurl: ""


markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge